let resList = [
  {
    id: 1,
    name: "Sharma's Biryani House",
    cuisine: ["Biryani", "Mughlai"],
    price: 250,
    rating: 4.4,
    deliveryTime: "30 mins",
    location: "Sector 12",
    image: "https://foodish-api.com/images/biryani/biryani14.jpg",
  },
  {
    id: 2,
    name: "Punjabi Rasoi",
    cuisine: ["North Indian", "Dal Makhani", "Paneer"],
    price: 300,
    rating: 4.1,
    deliveryTime: "35 mins",
    location: "Green Park",
    image: "https://foodish-api.com/images/butter-chicken/butter-chicken18.jpg",
  },
  {
    id: 3,
    name: "South Spice",
    cuisine: ["South Indian", "Dosa", "Idli"],
    price: 180,
    rating: 4.3,
    deliveryTime: "25 mins",
    location: "City Center",
    image: "https://foodish-api.com/images/dosa/dosa12.jpg",
  },
  {
    id: 4,
    name: "China Town Express",
    cuisine: ["Chinese", "Noodles", "Manchurian"],
    price: 220,
    rating: 4.0,
    deliveryTime: "28 mins",
    location: "Lake View Road",
    image: "https://foodish-api.com/images/pasta/pasta9.jpg",
  },
  {
    id: 5,
    name: "Tandoori Flames",
    cuisine: ["Tandoori", "Kebab", "BBQ"],
    price: 350,
    rating: 4.5,
    deliveryTime: "40 mins",
    location: "Sector 20",
    image: "https://foodish-api.com/images/butter-chicken/butter-chicken5.jpg",
  },
  {
    id: 6,
    name: "Italiano Pizzeria",
    cuisine: ["Pizza", "Italian"],
    price: 450,
    rating: 4.2,
    deliveryTime: "32 mins",
    location: "MG Road",
    image: "https://foodish-api.com/images/pizza/pizza21.jpg",
  },
  {
    id: 7,
    name: "Burger Hub",
    cuisine: ["Burgers", "Fast Food"],
    price: 200,
    rating: 4.1,
    deliveryTime: "22 mins",
    location: "Sector 9",
    image: "https://foodish-api.com/images/burger/burger14.jpg",
  },
  {
    id: 8,
    name: "The Dessert Room",
    cuisine: ["Desserts", "Ice Cream"],
    price: 150,
    rating: 4.6,
    deliveryTime: "20 mins",
    location: "City Square",
    image: "https://foodish-api.com/images/dessert/dessert2.jpg",
  },
  {
    id: 9,
    name: "Hyderabadi Kitchen",
    cuisine: ["Hyderabadi", "Biryani"],
    price: 270,
    rating: 4.3,
    deliveryTime: "33 mins",
    location: "Ring Road",
    image: "https://foodish-api.com/images/biryani/biryani9.jpg",
  },
  {
    id: 10,
    name: "Fresh Bowl Salads",
    cuisine: ["Healthy", "Salads"],
    price: 180,
    rating: 4.7,
    deliveryTime: "18 mins",
    location: "Eco Park Area",
    image: "https://picsum.photos/seed/salad123/400/300",
  },
  {
    id: 11,
    name: "Mexicano Fiesta",
    cuisine: ["Tacos", "Mexican"],
    price: 320,
    rating: 4.2,
    deliveryTime: "27 mins",
    location: "Metro Station Road",
    image: "https://picsum.photos/seed/mexican55/400/300",
  },
  {
    id: 12,
    name: "Royal Thali Palace",
    cuisine: ["Thali", "Indian"],
    price: 260,
    rating: 4.4,
    deliveryTime: "38 mins",
    location: "Old Market",
    image: "https://foodish-api.com/images/naan/naan5.jpg",
  },
  {
    id: 13,
    name: "Sushi Express",
    cuisine: ["Japanese", "Sushi"],
    price: 600,
    rating: 4.5,
    deliveryTime: "45 mins",
    location: "DLF Phase 3",
    image: "https://picsum.photos/seed/sushi44/400/300",
  },
  {
    id: 14,
    name: "Chai Adda",
    cuisine: ["Tea", "Snacks"],
    price: 90,
    rating: 4.0,
    deliveryTime: "15 mins",
    location: "BBD Bagh",
    image: "https://picsum.photos/seed/chai22/400/300",
  },
  {
    id: 15,
    name: "The Veg Kitchen",
    cuisine: ["Pure Veg", "Indian"],
    price: 210,
    rating: 4.3,
    deliveryTime: "28 mins",
    location: "Sector 5",
    image: "https://picsum.photos/seed/veg77/400/300",
  },
  {
    id: 16,
    name: "Coastal Delight",
    cuisine: ["Seafood", "Coastal"],
    price: 500,
    rating: 4.4,
    deliveryTime: "42 mins",
    location: "Beach Road",
    image: "https://picsum.photos/seed/seafood88/400/300",
  },
  {
    id: 17,
    name: "Kolkata Kathi Rolls",
    cuisine: ["Rolls", "Street Food"],
    price: 120,
    rating: 4.2,
    deliveryTime: "20 mins",
    location: "Park Street",
    image: "https://foodish-api.com/images/naan/naan2.jpg",
  },
  {
    id: 18,
    name: "Momos Point",
    cuisine: ["Momos", "Tibetan"],
    price: 130,
    rating: 4.1,
    deliveryTime: "23 mins",
    location: "Mall Road",
    image: "https://picsum.photos/seed/momos99/400/300",
  },
];

export default resList;
// export { resList, setResList };
